scrape_configs:

  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'backoffice_backend'
    scrape_interval: 5s
    static_configs:
      - targets: ['codeyani-php_ddd-backoffice_backend-php:8040']

  - job_name: 'backoffice_frontend'
    scrape_interval: 5s
    static_configs:
      - targets: ['codeyani-php_ddd-backoffice_frontend-php:8041']

  - job_name: 'mooc_backend'
    scrape_interval: 5s
    static_configs:
      - targets: ['codeyani-php_ddd-mooc_backend-php:8030']
