imports:
  - { resource: ../../../../src/Mooc/Shared/Infrastructure/Symfony/DependencyInjection/mooc_services.yaml }

services:
  _defaults:
    autoconfigure: true
    autowire: true

  # Configure
  _instanceof:
    Codeyani\Shared\Domain\Bus\Event\DomainEventSubscriber:
      tags: ['codeyani.domain_event_subscriber']

    Codeyani\Shared\Domain\Bus\Command\CommandHandler:
      tags: ['codeyani.command_handler']

    Codeyani\Shared\Domain\Bus\Query\QueryHandler:
      tags: ['codeyani.query_handler']

  Codeyani\Apps\Mooc\Backend\Controller\:
    resource: '../src/Controller'
    tags: ['controller.service_arguments']

  Codeyani\Apps\Mooc\Backend\Command\:
    resource: '../src/Command'
    tags: ['console.command']

  # Wire
  Codeyani\Shared\:
    resource: '../../../../src/Shared'

  Codeyani\Mooc\:
    resource: '../../../../src/Mooc'

  # -- TAGGING --
  Codeyani\Shared\Infrastructure\Bus\Event\InMemory\InMemorySymfonyEventBus:
    arguments: [!tagged codeyani.domain_event_subscriber]
    lazy: true

  Codeyani\Shared\Infrastructure\Bus\Event\DomainEventMapping:
    arguments: [!tagged codeyani.domain_event_subscriber]

  Codeyani\Shared\Infrastructure\Bus\Event\DomainEventSubscriberLocator:
    arguments: [!tagged codeyani.domain_event_subscriber]

  Codeyani\Shared\Infrastructure\Doctrine\DatabaseConnections:
    arguments: [!tagged codeyani.database_connection]

  Codeyani\Shared\Infrastructure\Symfony\AddJsonBodyToRequestListener:
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

  Codeyani\Shared\Infrastructure\Symfony\ApiExceptionListener:
    tags:
      - { name: kernel.event_listener, event: kernel.exception, method: onException }


  # -- APP DEFINITIONS --
  # Command/Query Handlers
  Codeyani\Shared\Infrastructure\Bus\Command\InMemorySymfonyCommandBus:
    arguments: [!tagged codeyani.command_handler]

  Codeyani\Shared\Infrastructure\Bus\Query\InMemorySymfonyQueryBus:
    arguments: [!tagged codeyani.query_handler]

  # RabbitMQ
  Codeyani\Shared\Infrastructure\Bus\Event\RabbitMq\RabbitMqConnection:
    arguments:
      - host: '%env(RABBITMQ_HOST)%'
        port: '%env(RABBITMQ_PORT)%'
        vhost: '%env(RABBITMQ_MOOC_VHOST)%'
        login: '%env(RABBITMQ_LOGIN)%'
        password: '%env(RABBITMQ_PASSWORD)%'
        read_timeout: 2
        write_timeout: 2
        connect_timeout: 5

  Codeyani\Shared\Infrastructure\Bus\Event\RabbitMq\RabbitMqEventBus:
    arguments: ['@Codeyani\Shared\Infrastructure\Bus\Event\RabbitMq\RabbitMqConnection', '%env(RABBITMQ_EXCHANGE)%']

  Codeyani\Shared\Infrastructure\Bus\Event\RabbitMq\RabbitMqDomainEventsConsumer:
    arguments:
      - '@Codeyani\Shared\Infrastructure\Bus\Event\RabbitMq\RabbitMqConnection'
      - '@Codeyani\Shared\Infrastructure\Bus\Event\DomainEventJsonDeserializer'
      - '%env(RABBITMQ_EXCHANGE)%'
      - '%env(RABBITMQ_MAX_RETRIES)%'

  Codeyani\Apps\Mooc\Backend\Command\DomainEvents\RabbitMq\ConfigureRabbitMqCommand:
    arguments:
      - '@Codeyani\Shared\Infrastructure\Bus\Event\RabbitMq\RabbitMqConfigurer'
      - '%env(RABBITMQ_EXCHANGE)%'
      - !tagged codeyani.domain_event_subscriber

  Codeyani\Shared\Infrastructure\Bus\Event\WithMonitoring\WithPrometheusMonitoringEventBus:
    arguments: ['@Codeyani\Shared\Infrastructure\Monitoring\PrometheusMonitor', 'mooc_backend', '@Codeyani\Shared\Infrastructure\Bus\Event\RabbitMq\RabbitMqEventBus']

  # -- IMPLEMENTATIONS SELECTOR --
  Codeyani\Shared\Domain\Bus\Event\EventBus: '@Codeyani\Shared\Infrastructure\Bus\Event\WithMonitoring\WithPrometheusMonitoringEventBus'
