services:
  # Databases
  Doctrine\ORM\EntityManager:
    factory: [ Codeyani\Mooc\Shared\Infrastructure\Doctrine\MoocEntityManagerFactory, create ]
    arguments:
      - driver: '%env(MOOC_DATABASE_DRIVER)%'
        host: '%env(MOOC_DATABASE_HOST)%'
        port: '%env(MOOC_DATABASE_PORT)%'
        dbname: '%env(MOOC_DATABASE_NAME)%'
        user: '%env(MOOC_DATABASE_USER)%'
        password: '%env(MOOC_DATABASE_PASSWORD)%'
      - '%env(APP_ENV)%'
    tags:
      - { name: codeyani.database_connection }
    public: true


  # Users
  Codeyani\Mooc\Users\Domain\UserRepository: '@Codeyani\Mooc\Users\Infrastructure\Persistence\DoctrineUserRepository'
